### ISSUE TITLE
Configure GET and POST request for hikes

### ISSUE THREAD

**Issue by srietkerk** [MaggieYang57/CSC308-TeamB#29]
Estimate 2-3 hours.

**Comment by Baagi** [comment]
Actual time spent 4 hours. 

Transitioned to using Express.js instead of Flask.
 - Took a bit time to learn and setup Express.js: 1-2 hours.
 - Setting up the API endpoints: 1-2 hours.

**Comment by Baagi** [comment]
Closed the issue since we did them in #33 and #34.
