### ISSUE TITLE
Filter Hikes by Tags

### ISSUE THREAD

**Issue by MaggieYang57** [MaggieYang57/CSC308-TeamB#4]
As a dog owner, I want to filter hikes based on which are dog-friendly so that I know whether or not I can bring my dog along with me.

**Comment by srietkerk** [comment]
Sprint 2:
Estimated time: 3 hours
Actual time: ongoing

**Comment by srietkerk** [comment]
Sprint 3:
Estimated total time (as a continuation from Sprint 2): 3 days
Actual time:  3 days
