### ISSUE TITLE
Filter Hikes - Difficulty

### ISSUE THREAD

**Issue by MaggieYang57** [MaggieYang57/CSC308-TeamB#8]
As a person who is new to the local hiking area, I want to be able to see how each hike is ranked in terms of difficulty so I know which hike I should choose based on my current skill level.

**Comment by srietkerk** [comment]
Estimated time - 5 hours
Actual time - 5 hours

**Comment by srietkerk** [comment]
We actually moved from a filter to a sort by difficulty
